### ISSUE TITLE
Wrong parameter when initializing with data file

### ISSUE THREAD

**Issue by nwhitehair** [sigmf/sigmf-python#10]
When a `SigMFFile` object is created with a pre-exisiting data file, the `skip_checksum` argument is passed in the wrong position to the `set_data_file` method. This incorrectly sets the value of the `data_buffer` parameter instead and causes `skip_checksum` to always take its default value when initializing with data.

PR #9 fixes the problem by passing `skip_checksum` by name instead of by position.

**Comment by Netherdrake** [comment]
I get the same error on `collection.get_SigMFFile` with `sigmf = {editable = true, ref = "initialization-bugfix", git = "https://github.com/nwhitehair/sigmf-python"}
` as well
