### ISSUE TITLE
Can Bandwidth SCS etc be used in Sigmf-meta for sigmf-python

### ISSUE THREAD

**Issue by amulamoottil** [sigmf/sigmf-python#16]
Hi there,
Can Bandwidth SCS etc be used in Sigmf-meta

**Comment by Teque5** [comment]
I believe you are asking if metadata like subcarrier spacing bandwidth is supported with sigmf. The answer is not in the main specification, but it's easy (**and allowed**) to add custom metadata to a SigMF object. This can be done willy-nilly with a key like `amulamoottil:subcarrier_spacing` or more formally with a SigMF extension. [Visit the specification](https://github.com/sigmf/SigMF/blob/sigmf-v1.x/sigmf-spec.md) to learn more about that.
