### ISSUE TITLE
Run workflow on PR events

### ISSUE THREAD

**Issue by bebau** [sigmf/sigmf-python#33]
Would be nice for contributors to have tests run on PR opening/commits added. It looks like pull request just needs to be added to the list here: 

https://github.com/sigmf/sigmf-python/blob/406eed771b578249190c2b780be594fa73f35045/.github/workflows/main.yml#L3

**Comment by Teque5** [comment]
Not too familiar with the syntax here. What exactly should be changed? You can make a PR if you know...
