### ISSUE TITLE
Problems installing v1.2.0

### ISSUE THREAD

**Issue by srs4511351** [sigmf/sigmf-python#52]
The prescribed method on installing sigmf-python is with pip.

pip installation is ess3ectially blocked on Debian Bookworm.

With v1.1.5, I used `sudo python3 setup.py install` but setup.py in not in the v1.2.0 release.

Is there another way to install sigmf-python? My distro does not have a sigmf-python package.

I did install it like this:
```
git checkout v1.1.5
sudo python3 setup.py install
```
However, I got the message: SetuptoolsDeprecationWarning: setup.py install is deprecated.

----Steve

**Comment by Teque5** [comment]
Using setuptools to install was never recommended, but I understand if you can't use `pip`.

Note it's generally bad practice to do a `sudo install` and folks usually use a user directory.

Modern alternatives to pip are `conda` and `poetry`. Before pip there was something called `easy_install`, but I'm not sure if that works anymore. I suspect you can avoid all this and install pip yourself as a user install running the `get-pip.py` script [found here](https://pip.pypa.io/en/stable/installation/).

The move away from setuptools started with [PEP518](https://peps.python.org/pep-0518/) in 2016 and we'll only be supporting pyproject now.

**Comment by gmabey** [comment]
I had been using the Ruby gem FPM to create a .eb package but that stopped
working a couple of months ago. You can see the issue I created at the FPM
GitHub page.

**Comment by Teque5** [comment]
> I installed it with pipx as suggests in the error message, but I can't get rid of version 1.1.5. setup.py does not have an uninstall. python still loads version 1.1.5.

You can manually install/uninstall by modifying the files inside your `site-packages/` or `dist-packages/` folder. For user installs this is in `.local/lib/<python_version>/` and for sudo installs in ubuntu is in `/usr/local/lib/<python_version/`. Unsure about other distributions.

**Comment by srs4511351** [comment]
The version 1.1.5 installation was gone after a reboot. (I forced pip to uninstall it although it was installed with setup,py)

pipx installs in a virtual environment. In python, import sigmf does not find sigmf in the default environment.
Virtual environments are a problem. They are difficult to use and the virtual environment would make all other modules unavailable.

I am using sigmf for an installed python program, so I won't modify that script.
So far, there is no good way to install and use sigmf on Debian Bookworm lacking a apt or .deb package.
