### ISSUE TITLE
README example does not run due to missing `VERSION_KEY`

### ISSUE THREAD

**Issue by james-pcdr** [sigmf/sigmf-python#65]
Hello all,
I'm just starting to learn about SigMF. I tried the ["Create and save..." example](https://github.com/sigmf/sigmf-python?tab=readme-ov-file#create-and-save-a-collection-of-sigmf-recordings-from-numpy-arrays) from the homepage, and it gave an error saying `'core:version' is a required property`.

Possible solutions:
1. Add the version to the example:
```python3
global_info = {
    SigMFFile.VERSION_KEY: "1.0.0",
    ...
```

2. Make 1.0.0 default? In [this comment](https://github.com/sigmf/sigmf-python/pull/55#issuecomment-2040825025), it looks like perhaps that was intended :man_shrugging:.

Thanks all for making SigMF!

**Comment by Teque5** [comment]
Yep I think we broke this just recently, need to create a bugfix.

It should use the `sigmf.__specification__` value, which is currently `1.2.0`.

Thanks for opening the issue.
