### ISSUE TITLE
get_captures function is running extremely slow

### ISSUE THREAD

**Issue by GreenK173** [sigmf/sigmf-python#74]
Is there any reason why the `get_captures` function in the `sigmffile.py` script is implemented as
```python
return [x for x in self._metadata.get(self.CAPTURE_KEY, [])]
```
instead of
```python
return self._metadata.get(self.CAPTURE_KEY, [])
```
? This makes massive difference in performance. I'm working with a dataset that has hundreds of thousands of captures, and while with the latter version loading of data from a capture takes a fraction of a second, with the current version it takes tens of minutes, making it unusable.

**Comment by Teque5** [comment]
Looking at git blame I don't see a reason why this was a list comprehension, but your proposed fix looks good so I'll open a PR.
