### ISSUE TITLE
ConnectTimeoutError when install 1.2.3 version

### ISSUE THREAD

**Issue by shinchik17** [sigmf/sigmf-python#80]
Getting ConnectTimeoutError when run `pip install sigmf` or `pip install sigmf==1.2.3`.
However `pip install sigmf==1.2.2` works perfect so that is not my network issue. I used Python 3.8.5. Setuptools version 72.0.0

I also made an experiment in Python 3.10.8 (setuptools==75.6.0) and have the same result - 1.2.2 installs and 1.2.3 does not.

Are there any requirements in new version that I should tbe aware of and satisfy?

**Comment by Teque5** [comment]
Hm `v1.2.3` is in the pypi registry and I can pip install over here just like you suggest. Perhaps there is an issue with some network route to where that particular package is being hosted on [pypi](https://pypi.org/).
