### ISSUE TITLE
SigMFCollection doesn't add specification version to the metadata

### ISSUE THREAD

**Issue by GreenK173** [sigmf/sigmf-python#82]
According to the [SigMF specification](https://sigmf.org/#subsec:SigMFCollectionFormat), the specification version is a required field in a collection metafile. However the currect version doesn't ensure that the field is present. The same issue for `SigMFFile` was dealt with in issue #65 and PR #67.

**Comment by Teque5** [comment]
Yes, a few tests for SigMFCollection are overdue to catch things like this.

**Comment by Teque5** [comment]
Thanks for opening the PR.
