### ISSUE TITLE
python 3.12 displays a deprecation warning for function get_sigmf_iso8601_datetime_now in utils.py

### ISSUE THREAD

**Issue by chrisjohgorman** [sigmf/sigmf-python#87]
When building with python 3.12.7 on arch, I get a deprecation warning

It says ...
```
sigmf/utils.py:23: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    return datetime.isoformat(datetime.utcnow()) + "Z"
```

I took a quick look around on how to fix this and it's fairly straight forward.

```
from datetime import datetime, timezone

def get_sigmf_iso8601_datetime_now() -> str:
    """Get current UTC time as iso8601 string"""
    if sys.version_info >= (3, 12):
        return datetime.now(timezone.utc).strftime(SIGMF_DATETIME_ISO8601_FMT)
    else:
        return datetime.isoformat(datetime.utcnow()) + "Z"
```

This would produce the same strings for both calls and I assume this would be the way to go.  There's also the option of using `.isoformat()` instead of `.strftime()` which produces a slightly different format string than `SIGMF_DATETIME_ISO8601_FMT`.  Instead of `"%Y-%m-%dT%H:%M:%S.%fZ"`, it produces `"%Y-%m-%dT%H:%M:%S.%f+00:00"`.  I'm not sure if this would work in other places in the code base though.

**Comment by Teque5** [comment]
Thanks for raising the issue. I just tried and it appears `datetime.datetime.now(datetime.timezone.utc)` works in `v3.7` through `v3.12` so we will just make that simple change.
